<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Pairing;
use App\Models\Product;
use App\Models\Restaurant;
use Illuminate\Database\Seeder;

/**
 * Importa la carta completa del Bar Jaen III desde el dump MySQL carta_v2_staging.
 * Restaurante origen: restaurant_id = 1 en la BD fuente.
 *
 * Uso:
 *   php artisan db:seed --class=BarJaenIIISeeder
 *
 * Nota: active=false = visible en la carta pública (lógica invertida heredada).
 */
class BarJaenIIISeeder extends Seeder
{
    public function run(): void
    {
        $restaurant = Restaurant::where('name', 'Bar Jaen III')->first();

        if (! $restaurant) {
            $this->command->error('No se encontró el restaurante "Bar Jaen III". Ejecuta antes: php artisan db:seed --class=RestaurantSeeder');
            return;
        }

        if (Category::where('restaurant_id', $restaurant->id)->exists()) {
            $this->command->info('Ya existen categorías para "Bar Jaen III". Omitiendo seeder.');
            return;
        }

        $rid = $restaurant->id;

        // ── MARIDAJES ──────────────────────────────────────────────────────────
        // clave = id original en la BD fuente (para referenciar desde productos)

        $pairings = [];

        $pairings[3] = Pairing::create([
            'restaurant_id' => $rid,
            'name'          => 'Albariño casa',
            'description'   => 'Uva: Albariño, Loureiro y Caiño blanco.',
            'active'        => false,
        ]);

        $pairings[4] = Pairing::create([
            'restaurant_id' => $rid,
            'name'          => 'Ribera Viña Mayor Roble',
            'description'   => 'Vista: Rubí intenso con brillo azulado. Nariz: Aromas de frutos rojos y negros entrelazados con ligeros tostados procedentes de su paso por madera. Boca: Jugoso, fresco. Con un final sabroso.',
            'active'        => false,
        ]);

        $pairings[5] = Pairing::create([
            'restaurant_id' => $rid,
            'name'          => 'Protos Crianza',
            'description'   => "Vendimia en cajas y selección manual. Fermentación alcohólica a baja temperatura (24-25 ºC) con levaduras autóctonas de nuestros mejores viñedos. Fermentación maloláctica parcial en barrica nueva de roble francés y americano.\n\nMínimo 12 meses en barrica. 33% barricas nuevas de roble Francés, 34% barricas Americanas y Francesas de un año, 33% barricas Americanas y Francesas de dos años.",
            'active'        => false,
        ]);

        // ── CATEGORÍAS ────────────────────────────────────────────────────────
        // clave = id original en la BD fuente

        $cats = [];

        $cats[3]  = Category::create(['restaurant_id' => $rid, 'name' => 'Embutidos bellota',              'active' => true,  'order' => 0]);
        $cats[4]  = Category::create(['restaurant_id' => $rid, 'name' => 'Entrantes',                      'active' => false, 'order' => 1]);
        $cats[5]  = Category::create(['restaurant_id' => $rid, 'name' => 'Mariscos',                       'active' => false, 'order' => 2]);
        $cats[6]  = Category::create(['restaurant_id' => $rid, 'name' => 'Raciones',                       'active' => false, 'order' => 3]);
        $cats[7]  = Category::create(['restaurant_id' => $rid, 'name' => 'Carnes',                         'active' => false, 'order' => 5]);
        $cats[8]  = Category::create(['restaurant_id' => $rid, 'name' => 'Pescados',                       'active' => false, 'order' => 4]);
        $cats[9]  = Category::create(['restaurant_id' => $rid, 'name' => 'Postres',                        'active' => false, 'order' => 7]);
        $cats[10] = Category::create(['restaurant_id' => $rid, 'name' => 'Helado',                         'active' => false, 'order' => 6]);
        $cats[14] = Category::create(['restaurant_id' => $rid, 'name' => 'Vinos Blancos',                  'active' => false, 'order' => 8]);
        $cats[16] = Category::create(['restaurant_id' => $rid, 'name' => 'VINOS ROSADOS',                  'active' => true,  'order' => 9]);
        $cats[17] = Category::create(['restaurant_id' => $rid, 'name' => 'Vinos Tintos',                   'active' => false, 'order' => 10]);
        $cats[28] = Category::create(['restaurant_id' => $rid, 'name' => 'MENUS DEGUSTACION',              'active' => true,  'order' => 11]);
        $cats[29] = Category::create(['restaurant_id' => $rid, 'name' => 'MENU INFANTIL (Hasta 12 años)',  'active' => true,  'order' => 12]);
        $cats[30] = Category::create(['restaurant_id' => $rid, 'name' => 'PARA LOS MAS PEQUES',            'active' => false, 'order' => 13]);

        // ── HELPER ────────────────────────────────────────────────────────────

        $p = fn (array $d) => Product::create(array_merge($d, ['restaurant_id' => $rid]));
        $cat = fn (int $id) => $cats[$id]->id;
        $pair = fn (?int $id) => $id ? $pairings[$id]->id : null;

        // ── PRODUCTOS ─────────────────────────────────────────────────────────
        // active=false → visible en carta pública (lógica heredada)

        // Entrantes (cat 4)
        $p(['name' => 'Queso Manchego',                             'description' => 'Queso manchego curado SIN PASTEURIZAR.',                                                                                           'active' => false, 'offer' => false, 'order' => 2,  'featured' => false, 'recommended' => true,  'price' => '12,00€',              'offer_price' => '10',     'aller' => 'Leche.',                                                                                                                                                                    'category_id' => $cat(4),  'pairing_id' => $pair(4)]);
        $p(['name' => 'Ensalada de la casa (Tomate Temporada con Ventresca)', 'description' => 'Tomate de TEMPORADA con Ventresca, regado con nuestra vinagreta especial.',                                             'active' => false, 'offer' => false, 'order' => 0,  'featured' => true,  'recommended' => false, 'price' => '14,00€',              'offer_price' => '14,00€', 'aller' => 'Pescado, Sulfitos (vinagre), especias. Contaminación cruzada gluten, Crustáceos y Molusco.',                                                                             'category_id' => $cat(4),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Ensalada Mixta',                             'description' => 'Ensalada mixta con cebolla, tomate y zanahoria rallada. Las imágenes son orientativas.',                                          'active' => false, 'offer' => true,  'order' => 3,  'featured' => false, 'recommended' => false, 'price' => '14,00 €',             'offer_price' => '12',     'offer_badge' => 'Oferta', 'offer_start' => '2026-04-08', 'offer_end' => '2026-04-23', 'aller' => 'Pescado, sulfitos (vinagre y trazas en la zanahoria) y trazas de crustáceos, lactosa, frutos de cáscara, apio y soja.',                                                'category_id' => $cat(4),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Sopa de Marisco',                            'description' => 'Sopa de Mariscos preparada con ingredientes frescos y seleccionados.',                                                             'active' => false, 'offer' => false, 'order' => 1,  'featured' => false, 'recommended' => false, 'price' => '15,90€',              'offer_price' => '',       'aller' => 'Marisco.',                                                                                                                                                                  'category_id' => $cat(4),  'pairing_id' => $pair(3)]);
        $p(['name' => 'Mixta de Jamón 50% Iberico y Queso Manchego','description' => 'Queso manchego sin pasteurizar.',                                                                                                  'active' => false, 'offer' => false, 'order' => 9,  'featured' => false, 'recommended' => false, 'price' => '15,00€',              'offer_price' => '',       'aller' => 'Lácteos.',                                                                                                                                                                  'category_id' => $cat(4),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Jamón Cebo',                                 'description' => 'Jamón de campo 50x50 Ibérico.',                                                                                                    'active' => false, 'offer' => false, 'order' => 10, 'featured' => false, 'recommended' => false, 'price' => '17,00€',              'offer_price' => '23,00€', 'aller' => '',                                                                                                                                                                          'category_id' => $cat(4),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Ración de Pan',                              'description' => '"Pan fresco de panadería local, horneado cada día."',                                                                              'active' => true,  'offer' => false, 'order' => 5,  'featured' => false, 'recommended' => false, 'price' => '1,50€',               'offer_price' => '',       'aller' => 'Gluten. Puede contener trazas de frutos de cáscara y sésamo.',                                                                                                              'category_id' => $cat(4),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Parrillada de Verdura',                      'description' => 'Parrillada de verdura frescas del dia.',                                                                                           'active' => true,  'offer' => false, 'order' => 7,  'featured' => false, 'recommended' => false, 'price' => '16,00€',              'offer_price' => '12,00€', 'aller' => 'Posibles trazas de elaboración: Pescado y gluten.',                                                                                                                        'category_id' => $cat(4),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Embutidos bellota',                          'description' => 'Selección de embutidos de bellota.',                                                                                               'active' => false, 'offer' => false, 'order' => 0,  'featured' => false, 'recommended' => false, 'price' => '',                    'offer_price' => '',       'aller' => '',                                                                                                                                                                          'category_id' => $cat(3),  'pairing_id' => $pair(null)]);

        // Mariscos (cat 5)
        $p(['name' => 'Bigaros',                                    'description' => 'También conocido como caracol de mar. Se encuentran en las orillas y en las zonas próximas a las desembocaduras de los ríos.',    'active' => true,  'offer' => false, 'order' => 4,  'featured' => false, 'recommended' => false, 'price' => '12,50 €',             'offer_price' => '9,80€',  'aller' => 'Molusco. Posible presencia de trazas de elaboración Crustáceos, pescado y gluten.',                                                                                       'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Carabinero Extra Plancha',                   'description' => 'Carabinero EXTRA DE GRAN TAMAÑO.',                                                                                                 'active' => false, 'offer' => false, 'order' => 6,  'featured' => false, 'recommended' => false, 'price' => '19,00€ (100 GRAMOS)',  'offer_price' => '12,00€ pieza', 'aller' => 'Crustáceo. Posible presencia de trazas de elaboración Molusco, pescado y gluten.',                                                                                   'category_id' => $cat(5),  'pairing_id' => $pair(3)]);
        $p(['name' => 'Patas de buey',                              'description' => 'Pata de cangrejo Cocido. 250gr.',                                                                                                  'active' => false, 'offer' => false, 'order' => 8,  'featured' => false, 'recommended' => false, 'price' => '16,80€',              'offer_price' => '16,00€', 'aller' => 'Crustáceos y Sulfitos. Posible presencia de trazas de elaboración: pescado, Moluscos y gluten.',                                                                       'category_id' => $cat(5),  'pairing_id' => $pair(3)]);
        $p(['name' => 'Zamburiña (Viera Del Pacífico)',             'description' => 'La zamburiña posee una carne comestible. De tamaño inferior a la vieira, concentra un sabor y textura de mayor calidad.',        'active' => false, 'offer' => false, 'order' => 11, 'featured' => false, 'recommended' => false, 'price' => '3,90€ / Unidad',      'offer_price' => '2,90€',  'aller' => 'Molusco. Posible contaminación cruzada gluten y frutos secos, crustáceos y pescado.',                                                                                     'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Navaja gallega Fresca a la plancha',         'description' => 'Pescada capturada a buceo, una a una, sin redes ni golpes. Carne blanca, firme y jugosa, elaborada a la plancha en su punto justo.', 'active' => true, 'offer' => true, 'order' => 28, 'featured' => false, 'recommended' => false, 'price' => '19,50€',             'offer_price' => '16,90€', 'aller' => 'Molusco. Posible presencia de trazas de elaboración Crustáceos, pescado y gluten.',                                                                                       'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Berberecho al vapor',                        'description' => 'Berberecho. Tamaño mediano.',                                                                                                       'active' => true,  'offer' => true,  'order' => 29, 'featured' => false, 'recommended' => false, 'price' => '17,90€',              'offer_price' => '14,00€', 'aller' => 'Moluscos y Sulfitos. Gluten (posible contaminación cruzada).',                                                                                                         'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Langosta Plancha',                           'description' => 'Langosta gallega a la plancha.',                                                                                                   'active' => false, 'offer' => true,  'order' => 39, 'featured' => false, 'recommended' => false, 'price' => '13,00€ 100gr',        'offer_price' => '9,90€ 100gr.', 'aller' => 'Crustáceos. Posible presencia de trazas de elaboración moluscos, pescado y gluten.',                                                                              'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Percebe gallego Extra',                      'description' => 'Percebe gran tamaño gallego.',                                                                                                     'active' => false, 'offer' => true,  'order' => 47, 'featured' => false, 'recommended' => false, 'price' => '25,00€ (100 gramos)', 'offer_price' => '22,00€ (100 gramos)', 'aller' => 'Crustáceos, Molusco. Posible contaminación cruzada Harina y frutos secos y huevo.',                                                                        'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Cigala EXTRA PLANCHA',                       'description' => 'Cigala EXTRA GRAN TAMAÑO.',                                                                                                        'active' => false, 'offer' => false, 'order' => 48, 'featured' => false, 'recommended' => false, 'price' => '11,00€ (100 GRAMOS)', 'offer_price' => '12,90€ pieza', 'aller' => 'Crustáceo. Posible contaminación cruzada pescado, Molusco y gluten.',                                                                                          'category_id' => $cat(5),  'pairing_id' => $pair(3)]);
        $p(['name' => 'Almeja Marinera',                            'description' => 'Almeja con nuestro Fumet con un toque picante.',                                                                                   'active' => false, 'offer' => true,  'order' => 49, 'featured' => false, 'recommended' => false, 'price' => '23,00€',              'offer_price' => '17,90€', 'aller' => 'Molusco, sulfitos. Posible trazas de elaboración de crustáceos, pescado y gluten.',                                                                                   'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Nécora Cocida',                              'description' => 'Nécora, capturada en nasas.',                                                                                                      'active' => true,  'offer' => true,  'order' => 50, 'featured' => false, 'recommended' => false, 'price' => '15,00€ (100GR.)',     'offer_price' => '7,5€ (100Gr.)', 'aller' => 'Crustáceos. Posible presencia de trazas de elaboración Moluscos, pescado y gluten.',                                                                              'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Navaja a la plancha',                        'description' => 'Navaja gallega, congelada.',                                                                                                       'active' => false, 'offer' => false, 'order' => 53, 'featured' => false, 'recommended' => false, 'price' => '14,90€',              'offer_price' => '14,90€', 'aller' => 'Molusco. Posible presencia de trazas de elaboración Crustáceos, pescado y gluten.',                                                                                   'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Gamba Huelva Plancha Congelada',             'description' => 'Gamba Huelva Plancha Congelada.',                                                                                                  'active' => true,  'offer' => false, 'order' => 45, 'featured' => false, 'recommended' => false, 'price' => '18,50€',              'offer_price' => '16,00€', 'aller' => 'Crustáceos. Posible presencia de trazas de elaboración Molusco, pescado y gluten.',                                                                                   'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Bogavante Plancha Gallego',                  'description' => 'Bogavante Gallego plancha. Peso aproximado 600 gramos.',                                                                           'active' => false, 'offer' => false, 'order' => 61, 'featured' => false, 'recommended' => false, 'price' => '55,00€ pieza',        'offer_price' => '',       'aller' => 'Marisco, Crustáceos. Posible contaminación cruzada gluten.',                                                                                                                'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Viera Gallega',                              'description' => 'Viera Gallega.',                                                                                                                   'active' => true,  'offer' => true,  'order' => 64, 'featured' => false, 'recommended' => false, 'price' => '6,00€',               'offer_price' => '5,10',   'aller' => 'Molusco. Posible contaminación cruzada gluten, pescado y marisco.',                                                                                                      'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Gambon Plancha',                             'description' => 'Gambon plancha congelado en alta mar. Origen Argentina. FOTO ORIENTATIVA.',                                                       'active' => true,  'offer' => false, 'order' => 57, 'featured' => false, 'recommended' => false, 'price' => '14,00€',              'offer_price' => '14,00€', 'aller' => 'Sulfitos, Crustáceos. Posible presencia de trazas de elaboración moluscos, pescado y gluten.',                                                                           'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Ostra Gallega Rizada',                       'description' => 'Ostra gallega Rizada.',                                                                                                            'active' => true,  'offer' => true,  'order' => 58, 'featured' => false, 'recommended' => false, 'price' => '4,10€ pieza',         'offer_price' => '3,50€ Pieza', 'aller' => 'Molusco. Posible presencia de trazas de elaboración Crustáceos, pescado y gluten.',                                                                                 'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Gamba Blanca Plancha Villajoyosa',           'description' => '**GAMBA BLANCA DE VILLAJOYOSA** - Gamba seleccionada, llegada a diario y tratada como merece.',                                  'active' => false, 'offer' => false, 'order' => 71, 'featured' => false, 'recommended' => false, 'price' => '18,00€',              'offer_price' => '',       'aller' => 'Crustáceos. Posible presencia de trazas de elaboración Molusco, pescado y gluten.',                                                                                       'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Gamba Roja Huelva',                          'description' => 'Gamba Roja de Huelva.',                                                                                                            'active' => false, 'offer' => false, 'order' => 74, 'featured' => false, 'recommended' => false, 'price' => '12,00€ (100Gr)',      'offer_price' => '18,90€', 'aller' => 'Crustáceos. Posible presencia de trazas de elaboración Molusco, pescado y gluten.',                                                                                       'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Almeja Ajillo Extra',                        'description' => 'Almeja de gran tamaño, pesca a rastrillo Gallega. Con un toque picante.',                                                        'active' => true,  'offer' => true,  'order' => 78, 'featured' => false, 'recommended' => false, 'price' => '28,00€',              'offer_price' => '22,00€', 'aller' => 'Molusco. Posible presencia de trazas de elaboración Crustáceos, pescado y gluten.',                                                                                   'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Gamba al Ajillo',                            'description' => 'Gamba al ajillo.',                                                                                                                 'active' => false, 'offer' => false, 'order' => 79, 'featured' => false, 'recommended' => false, 'price' => '14,50€',              'offer_price' => '',       'aller' => 'Crustáceos. Posible presencia de trazas de elaboración moluscos, pescado y gluten.',                                                                                       'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Volandeira gallega Fresca (temporada)',      'description' => 'Volandeira Gallega fresca. TEMPORADA.',                                                                                            'active' => true,  'offer' => false, 'order' => 86, 'featured' => false, 'recommended' => false, 'price' => '3,95€ unidad',        'offer_price' => '3,00€',  'aller' => 'Molusco. Posible contaminación cruzada gluten y frutos secos, crustáceos y pescado.',                                                                                     'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Gamba blanca Congelada',                     'description' => 'Gamba Blanca congelada. Origen Grecia.',                                                                                           'active' => true,  'offer' => false, 'order' => 90, 'featured' => false, 'recommended' => false, 'price' => '19,75€',              'offer_price' => '13,80€', 'aller' => 'Sulfitos.',                                                                                                                                                                 'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Camaron Gallego Grande',                     'description' => 'Camarones gallegos medianos, cocidos al estilo clásico de las Rías Baixas, con ese toque salino que recuerda al auténtico sabor del Atlántico.', 'active' => true, 'offer' => true, 'order' => 92, 'featured' => false, 'recommended' => false, 'price' => '22,00 (100GR)', 'offer_price' => '13,60€ (100GR)', 'aller' => 'Marisco, Pescado. Posible contaminación cruzada Harina y frutos secos y huevo.', 'category_id' => $cat(5), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Centolla Cocida',                            'description' => 'Centolla fresca cocida. Arte de pesca nasas.',                                                                                     'active' => true,  'offer' => false, 'order' => 96, 'featured' => false, 'recommended' => false, 'price' => '3,80 (100GR)',        'offer_price' => '',       'aller' => 'Marisco, pescado, molusco, sulfitos.',                                                                                                                                      'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'langostino Tigre',                           'description' => 'Lo servimos tanto a la plancha como cocido.',                                                                                      'active' => true,  'offer' => false, 'order' => 101,'featured' => false, 'recommended' => false, 'price' => '12,00€',              'offer_price' => '',       'aller' => 'Molusco, marisco. Posible contaminación cruzada Gluten.',                                                                                                                   'category_id' => $cat(5),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Ostra Gallega',                              'description' => 'Ostra gallega Flor.',                                                                                                              'active' => true,  'offer' => false, 'order' => 100,'featured' => false, 'recommended' => false, 'price' => '4,50',                'offer_price' => '',       'aller' => 'Molusco. Posible contaminación cruzada pescado, Marisco, Harina.',                                                                                                          'category_id' => $cat(5),  'pairing_id' => $pair(null)]);

        // Raciones (cat 6)
        $p(['name' => 'Ancas de rana plancha o Fritas',             'description' => 'Las ancas de rana son un plato muy ligero para compartir. Las ancas rebozadas contienen gluten de harina.',                      'active' => false, 'offer' => false, 'order' => 14, 'featured' => false, 'recommended' => false, 'price' => '14,50€',              'offer_price' => '',       'aller' => 'Las ancas rebozadas contienen gluten. Posible presencia de trazas de elaboración Crustáceos, pescado y Molusco.',                                                         'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Boquerones Fritos',                          'description' => 'Boquerón del Cantábrico.',                                                                                                         'active' => false, 'offer' => false, 'order' => 14, 'featured' => false, 'recommended' => false, 'price' => '14,90€',              'offer_price' => '11,90€', 'aller' => 'Pescado, gluten. Posible presencia de trazas de elaboración Crustáceos y Moluscos.',                                                                                     'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Calamar Fresco Andaluza',                    'description' => 'Calamar fresco a la andaluza.',                                                                                                    'active' => false, 'offer' => true,  'order' => 12, 'featured' => false, 'recommended' => false, 'price' => '23,20 €',             'offer_price' => '19,30€', 'aller' => 'Molusco y gluten. Posible presencia de trazas de elaboración Crustáceos y pescado.',                                                                                    'category_id' => $cat(6),  'pairing_id' => $pair(3)]);
        $p(['name' => 'Croquetas de Gamba al Ajillo',               'description' => 'Croquetas de la Casa de gambas al Ajillo.',                                                                                       'active' => false, 'offer' => false, 'order' => 14, 'featured' => false, 'recommended' => false, 'price' => '13,20€',              'offer_price' => '10,00€', 'aller' => 'Crustáceos, pescado, gluten, sulfitos, leche y trazas de frutos de cáscara, huevo, soja y moluscos.',                                                                   'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Extra de salsa Ali olí',                     'description' => 'Con ajo. La imagen es orientativa.',                                                                                               'active' => false, 'offer' => false, 'order' => 14, 'featured' => false, 'recommended' => false, 'price' => '1,90 €',              'offer_price' => '',       'aller' => 'Huevo y trazas de trigo, soja, leche, apio, pescado y crustáceos.',                                                                                                         'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Patas de Calamar',                           'description' => 'Rejo de potón. Frito en aceite de oliva.',                                                                                         'active' => false, 'offer' => false, 'order' => 14, 'featured' => false, 'recommended' => false, 'price' => '15,10€',              'offer_price' => '',       'aller' => 'Gluten, Molusco.',                                                                                                                                                          'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Patatas ali-oli',                            'description' => 'Nuestras famosas patatas con salsa casera Ali-oli.',                                                                               'active' => false, 'offer' => false, 'order' => 15, 'featured' => false, 'recommended' => false, 'price' => '8,90€',               'offer_price' => '',       'aller' => 'Huevo y trazas de trigo, soja, leche, apio, pescado, crustáceos y moluscos.',                                                                                            'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Patatas bravas',                             'description' => 'Picantes.',                                                                                                                        'active' => false, 'offer' => false, 'order' => 16, 'featured' => false, 'recommended' => false, 'price' => '8,90€',               'offer_price' => '',       'aller' => 'Trazas de trigo, soja, leche, apio, pescado, crustáceos y moluscos, Almendra.',                                                                                          'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Patatas mixtas',                             'description' => 'Nuestras 2 salsas caseras mezcladas en un mismo plato.',                                                                           'active' => false, 'offer' => false, 'order' => 17, 'featured' => false, 'recommended' => false, 'price' => '8,90€',               'offer_price' => '',       'aller' => 'Trazas de trigo, soja, leche, apio, pescado, crustáceos y moluscos, almendra.',                                                                                          'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Pescado en adobo o bienmesabe',              'description' => 'Elaborado con majao de ajos, pimentón, comino, orégano y vinagre. Frito en aceite de oliva.',                                    'active' => true,  'offer' => false, 'order' => 18, 'featured' => false, 'recommended' => false, 'price' => '16,80€',              'offer_price' => '',       'aller' => 'Pescado, Gluten y sulfitos.',                                                                                                                                                'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Ración de Tortillita de camarón',            'description' => 'Tortillita de camarones: harina de trigo, harina de garbanzo, agua, sal, cebolleta, perejil y camarones. Frita en aceite.', 'active' => true,  'offer' => false, 'order' => 19, 'featured' => false, 'recommended' => false, 'price' => '11,00€ (4 Unidades)', 'offer_price' => '2,95€ Unidad', 'aller' => 'Gluten (trigo), crustáceos. Posible presencia de trazas de elaboración Molusco y Pescado.',                                                                          'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Chopito (Congelado)',                        'description' => 'Chopito Congelado. (Origen China).',                                                                                               'active' => true,  'offer' => false, 'order' => 38, 'featured' => false, 'recommended' => false, 'price' => '16,00€',              'offer_price' => '22,00€', 'aller' => 'Gluten y molusco. Posible presencia de trazas de elaboración Crustáceos, pescado.',                                                                                     'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Puntilla Fresca Nacional (Cadiz)',           'description' => 'Puntilla nacional Fresca. Origen Cádiz.',                                                                                          'active' => true,  'offer' => false, 'order' => 42, 'featured' => false, 'recommended' => false, 'price' => '26,90',               'offer_price' => '',       'aller' => 'Lácteos, gluten, frutos secos, mariscos, crustáceos y posible contaminación cruzada por elaboración.',                                                                    'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Chipirón Plancha',                           'description' => 'Calamar Pequeño de Playa a la plancha, con ajo laminado y nuestra salsa de la casa.',                                            'active' => true,  'offer' => false, 'order' => 51, 'featured' => false, 'recommended' => false, 'price' => '17,90€',              'offer_price' => '',       'aller' => 'Molusco. Posible presencia de trazas de elaboración Crustáceos, pescado y gluten.',                                                                                       'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Calamar Potera Gallego Plancha',             'description' => 'Calamar potera Gallego a la plancha. Peso en sucio aprox. 700gr.',                                                                'active' => true,  'offer' => true,  'order' => 54, 'featured' => false, 'recommended' => false, 'price' => '37,50€',              'offer_price' => '29,50€', 'aller' => 'Molusco. Posible presencia de trazas de elaboración Crustáceos, pescado y gluten.',                                                                                       'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Mejillón Tigre Artesano',                    'description' => 'Conchas de mejillón rellenas, rebozadas y fritas.',                                                                                'active' => false, 'offer' => false, 'order' => 56, 'featured' => false, 'recommended' => false, 'price' => '2,90€ unidad',        'offer_price' => '9,95',   'aller' => 'Pescado, Gluten, Molusco, Crustáceos, leche. Puede contener trazas de frutos de cáscara, huevo, soja y sulfitos.',                                                        'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Croquetas de jamón',                         'description' => 'Croqueta De Jamón Congelada.',                                                                                                     'active' => true,  'offer' => false, 'order' => 62, 'featured' => false, 'recommended' => false, 'price' => '9,90€',               'offer_price' => '',       'aller' => 'Gluten, lácteos, huevo. Trazas de crustáceo, pescado, soja, apio, sulfatos y moluscos.',                                                                                   'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Pulpo a la gallega',                         'description' => 'Pulpo de origen Marruecos.',                                                                                                       'active' => true,  'offer' => false, 'order' => 69, 'featured' => false, 'recommended' => false, 'price' => '26,50€',              'offer_price' => '26,50€', 'aller' => 'Sulfitos.',                                                                                                                                                                 'category_id' => $cat(6),  'pairing_id' => $pair(3)]);
        $p(['name' => 'Buñuelo de Bacalao',                         'description' => 'Buñuelos de Bacalao Caseros.',                                                                                                     'active' => true,  'offer' => false, 'order' => 93, 'featured' => false, 'recommended' => false, 'price' => '2,85 (Unidad)',        'offer_price' => '',       'aller' => 'Pescado, gluten, lácteos. Posible contaminación cruzada Marisco y Frutos secos.',                                                                                          'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Sepia gallega Fresca a la Plancha',          'description' => 'Sepia Fresca gallega. Estamos en temporada.',                                                                                      'active' => true,  'offer' => false, 'order' => 94, 'featured' => false, 'recommended' => false, 'price' => '23,00€',              'offer_price' => '',       'aller' => 'Posible contaminación cruzada Molusco, pescado, gluten y marisco.',                                                                                                          'category_id' => $cat(6),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Calamar Andaluza (Pota Argentina)',          'description' => 'Pota Argentina congelada.',                                                                                                        'active' => true,  'offer' => false, 'order' => 99, 'featured' => false, 'recommended' => false, 'price' => '15,00',               'offer_price' => '',       'aller' => 'Gluten, Sulfitos. Contaminación cruzada pescado y marisco.',                                                                                                                'category_id' => $cat(6),  'pairing_id' => $pair(null)]);

        // Carnes (cat 7)
        $p(['name' => 'Chuletas de cordero lechal Riaza',           'description' => 'Chuletas de cordero de lechal Segovia (Riaza).',                                                                                  'active' => false, 'offer' => true,  'order' => 20, 'featured' => false, 'recommended' => false, 'price' => '26,00€',              'offer_price' => '22,50€', 'aller' => 'Posible presencia de trazas de elaboración Crustáceos, pescado, Molusco y gluten.',                                                                                     'category_id' => $cat(7),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Entrecot Parrilla Lomo Bajo',                'description' => '"Tenemos entrecot de vaca Lomo bajo a la parrilla, con patatas caseras."',                                                       'active' => true,  'offer' => false, 'order' => 21, 'featured' => false, 'recommended' => false, 'price' => '16,00€',              'offer_price' => '15,00€', 'aller' => 'Posible contaminación cruzada: Pescado, Marisco, Gluten.',                                                                                                                  'category_id' => $cat(7),  'pairing_id' => $pair(4)]);
        $p(['name' => 'Entrecot de Wagyu Beef Gold (Marmoleado 5)', 'description' => 'Exquisita carne de Wagyu. Su grado de marmoleado 5 ofrece un equilibrio perfecto entre jugosidad y textura. Una experiencia gourmet única.', 'active' => true, 'offer' => true, 'order' => 36, 'featured' => false, 'recommended' => false, 'price' => '75,00€', 'offer_price' => '50,00€', 'aller' => 'Posible contaminación cruzada frutos secos y harina.', 'category_id' => $cat(7), 'pairing_id' => $pair(5)]);
        $p(['name' => 'ENTRECOT GALLEGO 100% DE PASTO',             'description' => "Carne excepcional de reses criadas en fincas particulares, en libertad y alimentación natural, sin pienso.\nSabor profundo, terneza real y calidad que se reconoce al primer corte.\nTAMBIEN SE SIRVE AL CORTE 58,00€ KG.", 'active' => true, 'offer' => false, 'order' => 52, 'featured' => false, 'recommended' => false, 'price' => '58,00€ kilo', 'offer_price' => '23,50€', 'aller' => '', 'category_id' => $cat(7), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Lomo de Ternera gallega a la Parrilla',      'description' => 'Cortado al gusto, servido a la Piedra.',                                                                                           'active' => true,  'offer' => true,  'order' => 59, 'featured' => false, 'recommended' => false, 'price' => '72,00€ kg.',          'offer_price' => '58,00€ Kg', 'aller' => 'Posible contaminación cruzada: Pescado, Marisco, Gluten.',                                                                                                          'category_id' => $cat(7),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Chuletón Añojo Fileteado Parrilla a la Piedra', 'description' => "Lomo de añojo a la parrilla.\nMarcado en parrilla viva y acompañado de patata panadera. Terminada en mesa a la piedra.", 'active' => true, 'offer' => false, 'order' => 65, 'featured' => false, 'recommended' => false, 'price' => '48,00€ KILO', 'offer_price' => '48,00€ KILO', 'aller' => 'Posible contaminación cruzada: Pescado, Marisco, Gluten.', 'category_id' => $cat(7), 'pairing_id' => $pair(4)]);
        $p(['name' => 'Solomillo Vaca a la Parrilla',               'description' => 'Solomillo de Vaca a la parrilla. Carbón de la dehesa de Extremadura. Peso aproximado 250GR.',                                    'active' => true,  'offer' => true,  'order' => 77, 'featured' => false, 'recommended' => false, 'price' => '25,00€',              'offer_price' => '19,90€', 'aller' => '',                                                                                                                                                                          'category_id' => $cat(7),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Txuleta de Vaca 20 días de Maduración',      'description' => 'Lomo de vaca con 20 días de maduración. Se sirve a la piedra.',                                                                  'active' => false, 'offer' => true,  'order' => 83, 'featured' => false, 'recommended' => false, 'price' => '76,00€',              'offer_price' => '63,00€ Kg.', 'aller' => '',                                                                                                                                                                      'category_id' => $cat(7),  'pairing_id' => $pair(5)]);
        $p(['name' => 'Tamahawk Parrilla (Recomendado 2/3 personas)', 'description' => "Peso 1kg-1,200kg. Recomendado 2-3 personas.\nLa carne Tomahawk es una de las piezas más deseadas en la mesa. Corte de las costillas delanteras de la res, conservando el hueso.", 'active' => true, 'offer' => true, 'order' => 89, 'featured' => false, 'recommended' => false, 'price' => '85,00€ kilo', 'offer_price' => '69,00€ kilo', 'aller' => '', 'category_id' => $cat(7), 'pairing_id' => $pair(5)]);
        $p(['name' => 'Churrasco de ternera a la Parrilla',         'description' => 'Falda de Ternera a la Parrilla. Peso Aproximado 400-450GR.',                                                                      'active' => true,  'offer' => false, 'order' => 91, 'featured' => false, 'recommended' => false, 'price' => '14,90€',              'offer_price' => '',       'aller' => '',                                                                                                                                                                          'category_id' => $cat(7),  'pairing_id' => $pair(null)]);
        $p(['name' => '1/2 Kilo de Chuletas de recental a la parrilla', 'description' => 'Chuletas de cordero de recental a la parrilla con patata panadera.',                                                         'active' => true,  'offer' => false, 'order' => 95, 'featured' => false, 'recommended' => false, 'price' => '19,90',               'offer_price' => '',       'aller' => '',                                                                                                                                                                          'category_id' => $cat(7),  'pairing_id' => $pair(5)]);
        $p(['name' => 'Lomo De Vaca a la Parrilla (A LA PIEDRA)',   'description' => 'Lomo de Vaca a la parrilla, seleccionando usted el corte de la pieza.',                                                           'active' => true,  'offer' => true,  'order' => 102,'featured' => false, 'recommended' => false, 'price' => '62,00€ KILO',         'offer_price' => '55,00€ KILO', 'aller' => '',                                                                                                                                                                  'category_id' => $cat(7),  'pairing_id' => $pair(null)]);

        // Pescados (cat 8)
        $p(['name' => 'Emperador Plancha',                          'description' => 'Emperador plancha.',                                                                                                               'active' => true,  'offer' => false, 'order' => 22, 'featured' => false, 'recommended' => false, 'price' => '15,50€',              'offer_price' => '12,80€', 'aller' => 'Pescado. Posible presencia de trazas de elaboración Crustáceos, Molusco y gluten.',                                                                                     'category_id' => $cat(8),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Lubina a la Espalda (Piscifactoría)',        'description' => 'Lubina a la Espalda. Foto orientativa.',                                                                                           'active' => true,  'offer' => false, 'order' => 46, 'featured' => false, 'recommended' => false, 'price' => '14,80€',              'offer_price' => '12,00€', 'aller' => 'Pescado. Posible presencia de trazas de elaboración Crustáceos, Molusco y gluten.',                                                                                     'category_id' => $cat(8),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Sardina plancha',                            'description' => 'Sardina Nacional.',                                                                                                                'active' => true,  'offer' => false, 'order' => 60, 'featured' => false, 'recommended' => false, 'price' => '7,00€',               'offer_price' => '5,00€',  'aller' => 'Pescado y posible contaminación cruzada gluten.',                                                                                                                          'category_id' => $cat(8),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Lubina Salvaje Gallega',                     'description' => 'Lubina de Pincho a la espalda.',                                                                                                   'active' => true,  'offer' => true,  'order' => 72, 'featured' => false, 'recommended' => false, 'price' => '22,00€',              'offer_price' => '16,00€', 'aller' => 'Pescado. Posible presencia de trazas de elaboración Crustáceos, Molusco y gluten.',                                                                                     'category_id' => $cat(8),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Lubina Stero (Recomendado 2 Personas)',      'description' => 'Lubina de Stero nacional.',                                                                                                        'active' => true,  'offer' => false, 'order' => 81, 'featured' => false, 'recommended' => false, 'price' => '14,95€ Persona',      'offer_price' => '18,50€', 'aller' => 'Pescado. Posible presencia de trazas de elaboración Crustáceos, Molusco y gluten.',                                                                                     'category_id' => $cat(8),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Lenguado Fino Gallego al Horno',             'description' => 'Con ensalada fresca.',                                                                                                             'active' => false, 'offer' => true,  'order' => 84, 'featured' => false, 'recommended' => false, 'price' => '21,90€',              'offer_price' => '19,90€', 'aller' => 'Pescado. Posible presencia de trazas de elaboración Crustáceos, Molusco y gluten.',                                                                                     'category_id' => $cat(8),  'pairing_id' => $pair(3)]);
        $p(['name' => 'Dorada de Stero bilbaína',                   'description' => 'Dorada Nacional de STERO (Islas Canarias).',                                                                                       'active' => true,  'offer' => false, 'order' => 97, 'featured' => false, 'recommended' => false, 'price' => '19,00€',              'offer_price' => '',       'aller' => 'Pescado, marisco. Posible contaminación cruzada Harina.',                                                                                                                   'category_id' => $cat(8),  'pairing_id' => $pair(null)]);

        // Postres (cat 9)
        $p(['name' => 'Tarta de queso',                             'description' => 'Tarta casera de queso al Horno.',                                                                                                  'active' => false, 'offer' => false, 'order' => 23, 'featured' => false, 'recommended' => false, 'price' => '7,40€',               'offer_price' => '',       'aller' => 'Leche, gluten (trigo) y sulfitos. Trazas de sésamo, soja y huevo.',                                                                                                         'category_id' => $cat(9),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Tarta de Zanahoria',                         'description' => 'Tarta de Zanahoria casera.',                                                                                                       'active' => true,  'offer' => false, 'order' => 44, 'featured' => false, 'recommended' => false, 'price' => '6,50€',               'offer_price' => '',       'aller' => 'Leche, Gluten. Trazas de sésamo, Soja, Huevo. Posible trazas de Pescado, Marisco y Moluscos.',                                                                           'category_id' => $cat(9),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Brownie con Helado de Vainilla y Nata',      'description' => 'Brownie Casero, servido con helado de vainilla y Chocolate.',                                                                     'active' => false, 'offer' => false, 'order' => 70, 'featured' => false, 'recommended' => false, 'price' => '7,50€',               'offer_price' => '',       'aller' => 'Gluten, trazas y frutos secos, leche y sus derivados. Posible contaminación cruzada.',                                                                                     'category_id' => $cat(9),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Flan casa',                                  'description' => 'Flan casero de queso.',                                                                                                            'active' => true,  'offer' => false, 'order' => 75, 'featured' => false, 'recommended' => false, 'price' => '4,50€',               'offer_price' => '',       'aller' => 'Lácteos, gluten, pescado, marisco. Posible contaminación cruzada.',                                                                                                         'category_id' => $cat(9),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Fresas con Nata',                            'description' => 'Fresa de Huelva.',                                                                                                                 'active' => true,  'offer' => false, 'order' => 76, 'featured' => false, 'recommended' => false, 'price' => '4,00€',               'offer_price' => '',       'aller' => 'Lácteos. Posible contaminación cruzada frutos secos.',                                                                                                                      'category_id' => $cat(9),  'pairing_id' => $pair(null)]);
        $p(['name' => 'SUGERENCIA Nuestro Postre (2-4 personas)',   'description' => 'Nuestro postre para compartir.',                                                                                                   'active' => false, 'offer' => false, 'order' => 80, 'featured' => false, 'recommended' => false, 'price' => '9.50€',               'offer_price' => '',       'aller' => 'Leche, gluten, frutos secos y derivados de la leche. Posible contaminación cruzada mariscos y pescado.',                                                                    'category_id' => $cat(9),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Tarta de pistacho y chocolate blanco',       'description' => 'Tarta de pistacho y chocolate blanco.',                                                                                            'active' => true,  'offer' => false, 'order' => 82, 'featured' => false, 'recommended' => false, 'price' => '6,90€',               'offer_price' => '',       'aller' => 'Leche, gluten (trigo) y sulfitos. Trazas de sésamo, soja y huevo.',                                                                                                         'category_id' => $cat(9),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Torrija de pan brioche y helado vainilla',   'description' => 'Torrija de pan brioche, nata, helado de vainilla sobre crema de mascarpone.',                                                     'active' => false, 'offer' => false, 'order' => 85, 'featured' => false, 'recommended' => false, 'price' => '8,50€',               'offer_price' => '',       'aller' => 'Lácteos, gluten. Posible contaminación cruzada.',                                                                                                                           'category_id' => $cat(9),  'pairing_id' => $pair(null)]);
        $p(['name' => 'Leche Fritas con helado de Vainilla',        'description' => 'Leche Frita con Helado de vainilla con nuestro topping.',                                                                         'active' => true,  'offer' => false, 'order' => 88, 'featured' => false, 'recommended' => false, 'price' => '5,50€',               'offer_price' => '',       'aller' => 'Glutén, leche y sus derivados, frutos secos. Posible contaminación cruzada marisco y pescado.',                                                                            'category_id' => $cat(9),  'pairing_id' => $pair(null)]);

        // Helado (cat 10)
        $p(['name' => 'Bombones helados',                           'description' => 'Bomboncitos de crujiente chocolate rellenos de helado de vainilla. Contiene 10 unidades.',                                       'active' => false, 'offer' => false, 'order' => 24, 'featured' => false, 'recommended' => false, 'price' => '6,80€',               'offer_price' => '',       'aller' => 'Leche y trazas de gluten, soja, huevo, cacahuetes y frutos de cáscara.',                                                                                                    'category_id' => $cat(10), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Extreme Vainilla y Chocolate Nestle',        'description' => 'Helado de vainilla chocolate con toppings de almendras y salsa de chocolate, con crujiente barquillo y punta de chocolate.',    'active' => false, 'offer' => false, 'order' => 25, 'featured' => false, 'recommended' => false, 'price' => '6,00 €',              'offer_price' => '',       'aller' => 'Gluten (trigo), leche, soja y frutos de cáscara (almendra). Trazas de otros frutos de cáscara.',                                                                           'category_id' => $cat(10), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Fantasmikos',                                'description' => 'Helado de agua y sorbetes de frutas con cobertura sabor a frutas (14,8%).',                                                       'active' => false, 'offer' => false, 'order' => 26, 'featured' => false, 'recommended' => false, 'price' => '4,80€',               'offer_price' => '',       'aller' => 'Leche y trazas de frutos secos.',                                                                                                                                           'category_id' => $cat(10), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Bombón Almendrado Nestle',                   'description' => 'Bombón almendrado Nestle.',                                                                                                        'active' => false, 'offer' => false, 'order' => 41, 'featured' => false, 'recommended' => false, 'price' => '6,00€',               'offer_price' => '',       'aller' => 'Gluten (trigo), leche, soja y frutos de cáscara (almendra). Trazas de otros frutos de cáscara.',                                                                           'category_id' => $cat(10), 'pairing_id' => $pair(null)]);

        // Vinos Blancos (cat 14)
        $p(['name' => 'Albariño Casa',                              'description' => 'Albariño de la casa. Uva: Albariño, Loureiro y Caiño blanco.',                                                                    'active' => false, 'offer' => false, 'order' => 30, 'featured' => false, 'recommended' => false, 'price' => '17,90€',              'offer_price' => '',       'aller' => 'Sulfitos.',                                                                                                                                                                 'category_id' => $cat(14), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Rueda D.O Protos',                           'description' => 'Color amarillo pajizo con matices verdosos. Aromas tropicales frescos como la piña y cítricos, junto a fruta blanca (manzana). Vino seco, fresco y con larga persistencia.', 'active' => false, 'offer' => false, 'order' => 31, 'featured' => false, 'recommended' => false, 'price' => '17,80€', 'offer_price' => '', 'aller' => 'Sulfitos.', 'category_id' => $cat(14), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Yllera 5',                                   'description' => 'Verdejo joven parcialmente fermentado, fresco, dulce, con una chispa de carbónico y con solo 5,5% de alcohol.',                 'active' => false, 'offer' => false, 'order' => 32, 'featured' => false, 'recommended' => false, 'price' => '17,00€',              'offer_price' => '',       'aller' => 'Sulfitos.',                                                                                                                                                                 'category_id' => $cat(14), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Martin Codax',                               'description' => 'Vino blanco D.O. Rías Baixas, 100% Albariño. Color amarillo verdoso brillante. Aromas cítricos maduros, fruta blanca y toques florales. Fresco, equilibrado y con acidez marcada.', 'active' => false, 'offer' => false, 'order' => 33, 'featured' => false, 'recommended' => false, 'price' => '26,00€', 'offer_price' => '', 'aller' => 'Sulfitos.', 'category_id' => $cat(14), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Godello',                                    'description' => 'Godello brillante, color amarillo pajizo. Aromas complejos: flores blancas, fruta blanca y herbáceos con fondo mineral. En boca, volumen, untuoso y redondo.', 'active' => false, 'offer' => false, 'order' => 55, 'featured' => false, 'recommended' => false, 'price' => '17,50€', 'offer_price' => '', 'aller' => 'Sulfitos.', 'category_id' => $cat(14), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Don Condado',                                'description' => 'Vino semi dulce. Condado de Huelva.',                                                                                               'active' => false, 'offer' => false, 'order' => 68, 'featured' => false, 'recommended' => false, 'price' => '14,00€',              'offer_price' => '',       'aller' => 'Sulfitos.',                                                                                                                                                                 'category_id' => $cat(14), 'pairing_id' => $pair(null)]);

        // Vinos Tintos (cat 17)
        $p(['name' => 'Pinna Fidelis Roble',                        'description' => "Vendimia manual con selección de racimos. Variedad: Tinta del País 100%. Crianza: 4 meses (barricas de roble americano). Grado: 13,5-14% Vol.", 'active' => false, 'offer' => false, 'order' => 43, 'featured' => false, 'recommended' => false, 'price' => '20,00€', 'offer_price' => '', 'aller' => 'Sulfitos.', 'category_id' => $cat(17), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Rioja Ramón Bilbao Crianza',                 'description' => 'Vino ligero, fresco y con buena intensidad frutal (moras, ciruelas). Notas de regaliz, vainilla y panadería. Elegante, jugoso y muy fácil de beber.', 'active' => false, 'offer' => false, 'order' => 63, 'featured' => false, 'recommended' => false, 'price' => '22,00€', 'offer_price' => '', 'aller' => 'Sulfitos.', 'category_id' => $cat(17), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Tinto casa',                                 'description' => 'Vino tinto. Uva tempranillo.',                                                                                                     'active' => false, 'offer' => false, 'order' => 66, 'featured' => false, 'recommended' => false, 'price' => '12,00€',              'offer_price' => '',       'aller' => 'Sulfitos.',                                                                                                                                                                 'category_id' => $cat(17), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Ribera del Duero Matarromera Crianza',       'description' => 'Matarromera Crianza, vino tinto de la Ribera del Duero. 100% tempranillo. Premio Mejor Vino del Mundo en 1994.',                 'active' => false, 'offer' => false, 'order' => 67, 'featured' => false, 'recommended' => false, 'price' => '40,00€',              'offer_price' => '35,00€', 'aller' => 'Sulfitos.',                                                                                                                                                                 'category_id' => $cat(17), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Protos Roble',                               'description' => 'Muy expresivo, potente y complejo. Fruta fresca, especias dulces, notas de bayas rojas. Sabor intenso, afrutado, con taninos redondos y buen final.', 'active' => false, 'offer' => false, 'order' => 73, 'featured' => false, 'recommended' => false, 'price' => '22,00€', 'offer_price' => '', 'aller' => 'Sulfitos.', 'category_id' => $cat(17), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Protos Crianza',                             'description' => "Mínimo 12 meses en barrica. 33% barricas nuevas de roble Francés, 34% barricas Americanas y Francesas de un año, 33% de dos años.", 'active' => false, 'offer' => false, 'order' => 87, 'featured' => false, 'recommended' => false, 'price' => '27,90€', 'offer_price' => '', 'aller' => 'Sulfitos.', 'category_id' => $cat(17), 'pairing_id' => $pair(null)]);

        // Para los más peques (cat 30)
        $p(['name' => 'Alitas de pollo Fritas',                     'description' => 'Alas de pollo Fresca de pollo nacionales. La ración es 1 kg.',                                                                    'active' => false, 'offer' => false, 'order' => 13, 'featured' => false, 'recommended' => false, 'price' => '13,90€',              'offer_price' => '11,00€', 'aller' => 'Posible presencia de trazas de elaboración Crustáceos, pescado, molusco y gluten.',                                                                                     'category_id' => $cat(30), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Fingers de pollo',                           'description' => 'Pollo empanado.',                                                                                                                  'active' => true,  'offer' => false, 'order' => 27, 'featured' => false, 'recommended' => false, 'price' => '9,50',                'offer_price' => '6,00€',  'aller' => 'Gluten (trigo), huevo. Posible contaminación cruzada marisco y pescado.',                                                                                                 'category_id' => $cat(30), 'pairing_id' => $pair(null)]);
        $p(['name' => 'Hamburguesa',                                'description' => 'Hamburguesa de ternera, sin salsa ni extras.',                                                                                     'active' => false, 'offer' => false, 'order' => 98, 'featured' => false, 'recommended' => false, 'price' => '7,00',                'offer_price' => '',       'aller' => 'Gluten.',                                                                                                                                                                   'category_id' => $cat(30), 'pairing_id' => $pair(null)]);

        $this->command->info('✓ Bar Jaen III importado: ' . Category::where('restaurant_id', $rid)->count() . ' categorías, ' . Product::where('restaurant_id', $rid)->count() . ' productos, ' . Pairing::where('restaurant_id', $rid)->count() . ' maridajes.');
    }
}
