<?php

namespace App\Support;

class DemoContent
{
    public static function categories(): array
    {
        return [
            ['name' => 'Entrantes',  'order' => 1],
            ['name' => 'Carnes',     'order' => 2],
            ['name' => 'Pescados',   'order' => 3],
            ['name' => 'Postres',    'order' => 4],
            ['name' => 'Bebidas',    'order' => 5],
        ];
    }

    /**
     * @return array<array{name:string,description:string,price:string,category:string,photo:string|null,allergens:string[],featured:bool,recommended:bool,order:int}>
     */
    public static function products(): array
    {
        return [
            // Entrantes
            [
                'name'        => 'Croquetas de jamón',
                'description' => 'Croquetas caseras de jamón ibérico con bechamel cremosa.',
                'price'       => '9,50 €',
                'category'    => 'Entrantes',
                'photo'       => 'demo/croquetas-jamon.jpg',
                'allergens'   => ['cereales-gluten', 'lacteos', 'huevos'],
                'featured'    => true,
                'recommended' => false,
                'order'       => 1,
            ],
            [
                'name'        => 'Pan con tomate',
                'description' => 'Pan de cristal con tomate rallado, aceite de oliva virgen extra y sal en escamas.',
                'price'       => '4,50 €',
                'category'    => 'Entrantes',
                'photo'       => 'demo/pan-tomate.jpg',
                'allergens'   => ['cereales-gluten'],
                'featured'    => false,
                'recommended' => true,
                'order'       => 2,
            ],
            [
                'name'        => 'Ensalada mixta',
                'description' => 'Lechuga, tomate, cebolla, aceitunas, atún y huevo duro.',
                'price'       => '8,00 €',
                'category'    => 'Entrantes',
                'photo'       => 'demo/ensalada-mixta.jpg',
                'allergens'   => ['huevos', 'pescado'],
                'featured'    => false,
                'recommended' => false,
                'order'       => 3,
            ],
            [
                'name'        => 'Tabla de embutidos',
                'description' => 'Selección de embutidos ibéricos: jamón, chorizo, salchichón y lomo.',
                'price'       => '14,00 €',
                'category'    => 'Entrantes',
                'photo'       => 'demo/tabla-embutidos.jpg',
                'allergens'   => [],
                'featured'    => false,
                'recommended' => false,
                'order'       => 4,
            ],
            // Carnes
            [
                'name'        => 'Entrecot a la plancha',
                'description' => 'Entrecot de ternera a la plancha con patatas fritas y pimientos asados.',
                'price'       => '22,00 €',
                'category'    => 'Carnes',
                'photo'       => 'demo/entrecot.jpg',
                'allergens'   => [],
                'featured'    => true,
                'recommended' => false,
                'order'       => 1,
            ],
            [
                'name'        => 'Pollo al ajillo',
                'description' => 'Muslos de pollo dorados con ajo, vino blanco y perejil.',
                'price'       => '14,00 €',
                'category'    => 'Carnes',
                'photo'       => 'demo/pollo-ajillo.jpg',
                'allergens'   => ['cereales-gluten', 'sulfitos'],
                'featured'    => false,
                'recommended' => true,
                'order'       => 2,
            ],
            [
                'name'        => 'Secreto ibérico',
                'description' => 'Secreto ibérico a la brasa con ensalada de rúcula y tomates cherry.',
                'price'       => '18,50 €',
                'category'    => 'Carnes',
                'photo'       => 'demo/secreto-iberico.jpg',
                'allergens'   => [],
                'featured'    => false,
                'recommended' => false,
                'order'       => 3,
            ],
            [
                'name'        => 'Carrilleras al vino tinto',
                'description' => 'Carrilleras de cerdo estofadas en vino tinto con puré de patata.',
                'price'       => '17,00 €',
                'category'    => 'Carnes',
                'photo'       => 'demo/carrilleras-vino.jpg',
                'allergens'   => ['cereales-gluten', 'sulfitos', 'lacteos'],
                'featured'    => false,
                'recommended' => false,
                'order'       => 4,
            ],
            // Pescados
            [
                'name'        => 'Merluza a la romana',
                'description' => 'Filetes de merluza rebozados con ensalada y limón.',
                'price'       => '16,00 €',
                'category'    => 'Pescados',
                'photo'       => 'demo/merluza-romana.jpg',
                'allergens'   => ['pescado', 'cereales-gluten', 'huevos'],
                'featured'    => false,
                'recommended' => false,
                'order'       => 1,
            ],
            [
                'name'        => 'Gambas al ajillo',
                'description' => 'Gambas salteadas con ajo, guindilla y aceite de oliva. Para mojar pan.',
                'price'       => '15,50 €',
                'category'    => 'Pescados',
                'photo'       => 'demo/gambas-ajillo.jpg',
                'allergens'   => ['crustaceos'],
                'featured'    => true,
                'recommended' => false,
                'order'       => 2,
            ],
            [
                'name'        => 'Pulpo a la gallega',
                'description' => 'Pulpo cocido sobre cama de patata, pimentón de la vera y aceite de oliva.',
                'price'       => '18,00 €',
                'category'    => 'Pescados',
                'photo'       => 'demo/pulpo-gallega.jpg',
                'allergens'   => ['moluscos'],
                'featured'    => false,
                'recommended' => true,
                'order'       => 3,
            ],
            [
                'name'        => 'Lubina al horno',
                'description' => 'Lubina entera al horno con patatas panaderas y verduras.',
                'price'       => '21,00 €',
                'category'    => 'Pescados',
                'photo'       => 'demo/lubina-horno.jpg',
                'allergens'   => ['pescado'],
                'featured'    => false,
                'recommended' => false,
                'order'       => 4,
            ],
            // Postres
            [
                'name'        => 'Crema catalana',
                'description' => 'Crema catalana con azúcar caramelizado al momento.',
                'price'       => '6,00 €',
                'category'    => 'Postres',
                'photo'       => 'demo/crema-catalana.jpg',
                'allergens'   => ['huevos', 'lacteos'],
                'featured'    => false,
                'recommended' => true,
                'order'       => 1,
            ],
            [
                'name'        => 'Tarta de queso',
                'description' => 'Tarta de queso al horno estilo La Viña, cremosa y con poca base.',
                'price'       => '6,50 €',
                'category'    => 'Postres',
                'photo'       => 'demo/tarta-queso.jpg',
                'allergens'   => ['lacteos', 'huevos', 'cereales-gluten'],
                'featured'    => true,
                'recommended' => false,
                'order'       => 2,
            ],
            [
                'name'        => 'Brownie con helado',
                'description' => 'Brownie de chocolate templado con bola de helado de vainilla.',
                'price'       => '7,00 €',
                'category'    => 'Postres',
                'photo'       => 'demo/brownie-helado.jpg',
                'allergens'   => ['cereales-gluten', 'huevos', 'lacteos', 'frutos-cascara'],
                'featured'    => false,
                'recommended' => false,
                'order'       => 3,
            ],
            // Bebidas
            [
                'name'        => 'Agua mineral',
                'description' => 'Agua mineral natural o con gas. Botella 50 cl.',
                'price'       => '2,00 €',
                'category'    => 'Bebidas',
                'photo'       => 'demo/agua-mineral.jpg',
                'allergens'   => [],
                'featured'    => false,
                'recommended' => false,
                'order'       => 1,
            ],
            [
                'name'        => 'Vino de la casa',
                'description' => 'Vino tinto, blanco o rosado de la casa. Copa o jarra.',
                'price'       => '3,00 €',
                'category'    => 'Bebidas',
                'photo'       => 'demo/vino-casa.jpg',
                'allergens'   => ['sulfitos'],
                'featured'    => false,
                'recommended' => false,
                'order'       => 2,
            ],
            [
                'name'        => 'Cerveza',
                'description' => 'Cerveza rubia en caña o botellín.',
                'price'       => '2,50 €',
                'category'    => 'Bebidas',
                'photo'       => 'demo/cerveza.jpg',
                'allergens'   => ['cereales-gluten'],
                'featured'    => false,
                'recommended' => false,
                'order'       => 3,
            ],
        ];
    }
}
